# Generated by Django 5.2.1 on 2026-06-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowerAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(help_text='Уникальный артикул товара', max_length=100, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, help_text='Рекомендуемая розничная цена', max_digits=12, verbose_name='Цена (РРЦ)')),
                ('category', models.CharField(blank=True, max_length=200, null=True, verbose_name='Категория')),
                ('photos', models.JSONField(blank=True, help_text='Список URL-адресов фотографий (JSON)', null=True, verbose_name='Фотографии')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на товар')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='Остатки')),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Производитель')),
                ('product_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вид изделия')),
                ('profile_color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет профиля')),
                ('material', models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал')),
                ('facade_material', models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал фасада')),
                ('body_material', models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал корпуса')),
                ('main_material', models.CharField(blank=True, max_length=200, null=True, verbose_name='Основной материал')),
                ('product_color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет изделия')),
                ('body_coating', models.CharField(blank=True, max_length=200, null=True, verbose_name='Покрытие корпуса')),
                ('has_shelf', models.BooleanField(default=False, verbose_name='Наличие полки')),
                ('rimless', models.BooleanField(default=False, verbose_name='Безободковый')),
                ('has_soft_close', models.BooleanField(default=False, verbose_name='Микролифт на сиденье')),
                ('has_armrest', models.BooleanField(default=False, verbose_name='Наличие подлокотника')),
                ('has_drawers', models.BooleanField(default=False, verbose_name='Наличие ящиков')),
                ('has_door_closers', models.BooleanField(default=False, verbose_name='Доводчики дверей')),
                ('has_drawer_closers', models.BooleanField(default=False, verbose_name='Доводчики ящика')),
                ('has_bidet', models.BooleanField(default=False, verbose_name='Встроенное биде')),
                ('seat_included', models.BooleanField(default=False, verbose_name='Сиденье в комплекте')),
                ('anti_splash', models.BooleanField(default=False, verbose_name='Система антивсплекс')),
                ('flush_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип смыва')),
                ('discharge_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип выпуска')),
                ('flush_mode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Режим смыва воды')),
                ('seat_material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Материал сиденья')),
                ('style', models.CharField(blank=True, max_length=100, null=True, verbose_name='Стиль')),
                ('sink_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип мойки')),
                ('washbasin_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип раковины')),
                ('mounting_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип монтажа')),
                ('collection', models.CharField(blank=True, max_length=200, null=True, verbose_name='Коллекция набора')),
                ('warranty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Гарантия')),
                ('brand', models.CharField(blank=True, max_length=200, null=True, verbose_name='Марка (Бренд)')),
                ('depth', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Глубина')),
                ('volume', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Объем')),
                ('drawer_count', models.IntegerField(blank=True, null=True, verbose_name='Количество ящиков')),
                ('tank_volume', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Объем бака в литрах')),
                ('length_mm', models.IntegerField(blank=True, null=True, verbose_name='Габариты длина, мм')),
                ('width_mm', models.IntegerField(blank=True, null=True, verbose_name='Габариты ширина, мм')),
                ('height_mm', models.IntegerField(blank=True, null=True, verbose_name='Габариты высота, мм')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
    ]
