# Generated by Django 5.2.1 on 2026-06-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanitaryequipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showerassembly',
            old_name='has_armrest',
            new_name='armrest',
        ),
        migrations.RenameField(
            model_name='showerassembly',
            old_name='has_bidet',
            new_name='built_in_bidet',
        ),
        migrations.RenameField(
            model_name='showerassembly',
            old_name='height_mm',
            new_name='dimensions_height',
        ),
        migrations.RenameField(
            model_name='showerassembly',
            old_name='length_mm',
            new_name='dimensions_length',
        ),
        migrations.RenameField(
            model_name='showerassembly',
            old_name='width_mm',
            new_name='dimensions_width',
        ),
        migrations.RenameField(
            model_name='showerassembly',
            old_name='has_door_closers',
            new_name='door_closers',
        ),
        migrations.RenameField(
            model_name='showerassembly',
            old_name='has_drawer_closers',
            new_name='drawer_closers',
        ),
        migrations.RenameField(
            model_name='showerassembly',
            old_name='drawer_count',
            new_name='drawers_count',
        ),
        migrations.RenameField(
            model_name='showerassembly',
            old_name='has_soft_close',
            new_name='seat_lift',
        ),
    ]
