# Generated by Django 5.2.1 on 2026-06-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitaryequipment', '0002_rename_has_armrest_showerassembly_armrest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showerassembly',
            name='anti_splash',
            field=models.CharField(verbose_name='Система антивсплекс'),
        ),
        migrations.AlterField(
            model_name='showerassembly',
            name='armrest',
            field=models.CharField(verbose_name='Наличие подлокотника'),
        ),
        migrations.AlterField(
            model_name='showerassembly',
            name='built_in_bidet',
            field=models.CharField(verbose_name='Встроенное биде'),
        ),
        migrations.AlterField(
            model_name='showerassembly',
            name='depth',
            field=models.CharField(blank=True, null=True, verbose_name='Глубина'),
        ),
        migrations.AlterField(
            model_name='showerassembly',
            name='dimensions_height',
            field=models.CharField(blank=True, null=True, verbose_name='Габариты высота, мм'),
        ),
        migrations.AlterField(
            model_name='showerassembly',
            name='dimensions_length',
            field=models.CharField(blank=True, null=True, verbose_name='Габариты длина, мм'),
        ),
        migrations.AlterField(
            model_name='showerassembly',
            name='dimensions_width',
            field=models.CharField(blank=True, null=True, verbose_name='Габариты ширина, мм'),
        ),
        migrations.AlterField(
            model_name='showerassembly',
            name='door_closers',
            field=models.CharField(verbose_name='Доводчики дверей'),
        ),
        migrations.AlterField(
            model_name='showerassembly',
            name='drawer_closers',
            field=models.CharField(verbose_name='Доводчики ящика'),
        ),
        migrations.AlterField(
            model_name='showerassembly',
            name='drawers_count',
            field=models.CharField(blank=True, null=True, verbose_name='Количество ящиков'),
        ),
        migrations.AlterField(
            model_name='showerassembly',
            name='has_drawers',
            field=models.CharField(verbose_name='Наличие ящиков'),
        ),
        migrations.AlterField(
            model_name='showerassembly',
            name='has_shelf',
            field=models.CharField(verbose_name='Наличие полки'),
        ),
        migrations.AlterField(
            model_name='showerassembly',
            name='photos',
            field=models.CharField(blank=True, null=True, verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='showerassembly',
            name='price',
            field=models.CharField(help_text='Рекомендуемая розничная цена', verbose_name='Цена (РРЦ)'),
        ),
        migrations.AlterField(
            model_name='showerassembly',
            name='rimless',
            field=models.CharField(verbose_name='Безободковый'),
        ),
        migrations.AlterField(
            model_name='showerassembly',
            name='seat_included',
            field=models.CharField(verbose_name='Сиденье в комплекте'),
        ),
        migrations.AlterField(
            model_name='showerassembly',
            name='seat_lift',
            field=models.CharField(verbose_name='Микролифт на сиденье'),
        ),
        migrations.AlterField(
            model_name='showerassembly',
            name='stock',
            field=models.CharField(blank=True, null=True, verbose_name='Остатки'),
        ),
        migrations.AlterField(
            model_name='showerassembly',
            name='tank_volume',
            field=models.CharField(blank=True, null=True, verbose_name='Объем бака в литрах'),
        ),
        migrations.AlterField(
            model_name='showerassembly',
            name='volume',
            field=models.CharField(blank=True, null=True, verbose_name='Объем'),
        ),
    ]
