# Generated by Django 5.2.1 on 2026-06-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitaryequipment', '0003_alter_showerassembly_anti_splash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showerassembly',
            name='category',
            field=models.CharField(blank=True, choices=[('shower', 'Душевая группа'), ('sink', 'Кухонные мойки'), ('furniture', 'Мебель'), ('sanitary', 'Санфаянс'), ('mixer', 'Смесители'), ('accessory', 'Сопутствующие товары')], max_length=200, null=True, verbose_name='Категория'),
        ),
    ]
