# Generated by Django 5.2.1 on 2026-06-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitaryequipment', '0004_alter_showerassembly_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showerassembly',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Категория'),
        ),
    ]
