# Generated by Django 5.2.1 on 2026-06-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitaryequipment', '0005_alter_showerassembly_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='showerassembly',
            name='type',
            field=models.CharField(default='plumbingFixtures', max_length=255),
        ),
    ]
