# Generated by Django 5.2.1 on 2026-06-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitaryequipment', '0006_showerassembly_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showerassembly',
            name='type',
            field=models.CharField(default='ShowerAssembly', max_length=255),
        ),
    ]
