# Generated by Django 5.2.1 on 2026-06-26 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanitaryequipment', '0009_rename_image1_showerassembly_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showerassembly',
            old_name='photos',
            new_name='image1',
        ),
    ]
