# Generated by Django 5.2.1 on 2026-06-26 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanitaryequipment', '0010_rename_photos_showerassembly_image1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showerassembly',
            old_name='image1',
            new_name='photos',
        ),
    ]
