# Generated by Django 5.2.1 on 2026-06-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitaryequipment', '0011_rename_image1_showerassembly_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='showerassembly',
            name='image1',
            field=models.CharField(blank=True, null=True, verbose_name='Фотографии'),
        ),
    ]
