# Generated by Django 5.2.1 on 2026-06-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitaryequipment', '0012_showerassembly_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showerassembly',
            name='image1',
            field=models.CharField(blank=True, null=True, verbose_name='Изображение 1'),
        ),
    ]
