# Generated by Django 5.2.1 on 2025-10-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0017_merge_20250729_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Новинка'),
        ),
    ]
