# Generated by Django 5.2.1 on 2026-06-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_newsletters',
            field=models.BooleanField(default=True, verbose_name='Получать рассылки'),
        ),
    ]
